### ISSUE TITLE
CTRL + Y broken on windows

### ISSUE THREAD

**Issue by farley911** [k--kato/vscode-intellij-idea-keybindings#71]
On Windows CTRL + Y is the shortcut for REDO, however your plug-in maps this to Delete line at caret. This makes undo then redo impossible and causes attempts to redo a change to delete entire lines costing you valuable development time as you manually recreate whatever code was deleted.

Looking at the VSCode keybindings for both Ctrl + Shift +Z and Ctrl + Y are bound to redo. Ctrl + Y is the most widely used binding for redo on windows machines and shouldn't be overwritten.

**Comment by farley911** [comment]
I guess IntelliJ used CTRL+SHIFT+Z for redo, horrible.

**Comment by k--kato** [comment]
I can't accept your request because of below pdf. But I can create a special build for you that removed Ctrl + Y.
* IntelliJ IDEA Default Keymap > Editing > Delete line at caret > Ctrl + Y
https://resources.jetbrains.com/storage/products/intellij-idea/docs/IntelliJIDEA_ReferenceCard.pdf

* removed Ctrl + Y build
[intellij-idea-keybindings-0.2.771.vsix.zip](https://github.com/k--kato/vscode-intellij-idea-keybindings/files/969060/intellij-idea-keybindings-0.2.771.vsix.zip)
